version: '3'

services:
  #Build do Node
  app:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    hostname: nodejsserver
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    image: node:alpine


  #Build do mysql
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  #Build do nginx
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge

volumes:
  exclude:
